#!/usr/bin/env bash
# ---------------------------------------------------------------------------
# update-actions-list.sh
#
# Uses `gh` CLI to discover all non-archived repos under github.com/actions/
# and fetch their latest release tags. Writes the result to:
#
#   <skill-dir>/actions-versions.md
#
# Prerequisites: `gh` authenticated and `jq` installed.
#
# Usage:
#   ./update-actions-list.sh [--dry-run] [--skill-dir <path>]
# ---------------------------------------------------------------------------
set -euo pipefail

DRY_RUN=false
SKILL_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"

while [[ $# -gt 0 ]]; do
  case "$1" in
    --dry-run)   DRY_RUN=true; shift ;;
    --skill-dir) SKILL_DIR="$2"; shift 2 ;;
    *) echo "Unknown arg: $1"; exit 1 ;;
  esac
done

VERSIONS_FILE="$SKILL_DIR/actions-versions.md"
TODAY=$(date +%Y-%m-%d)

# ---------------------------------------------------------------------------
# 1. Discover all non-archived repos from github.com/actions/
# ---------------------------------------------------------------------------
echo "==> Discovering repos from github.com/actions/ ..."

ALL_ACTIONS=()
while IFS=$'\t' read -r full_name; do
  [[ -z "$full_name" ]] && continue
  ALL_ACTIONS+=("$full_name")
done < <(
  gh api --paginate "orgs/actions/repos?sort=stars&per_page=100" \
    --jq '.[] | select(.archived==false) | .full_name' 2>/dev/null
)

echo "==> Found ${#ALL_ACTIONS[@]} actions total."

# ---------------------------------------------------------------------------
# 2. Fetch latest release tag for each action
# ---------------------------------------------------------------------------
declare -A DATA

echo "==> Fetching latest releases..."

for action in "${ALL_ACTIONS[@]}"; do
  printf '    %-45s ... ' "$action"

  tag=$(gh release view -R "$action" --json tagName -q '.tagName' 2>/dev/null || true)

  if [[ -z "$tag" ]]; then
    echo "no release"
    DATA["$action"]="N/A|N/A|$TODAY"
    continue
  fi

  # Extract major version number: v4.2.3 → 4
  major=$(echo "$tag" | sed -nE 's/^v?([0-9]+).*$/\1/p')
  [[ -z "$major" ]] && major="$tag"

  echo "$tag  (major: $major)"
  DATA["$action"]="$tag|$major|$TODAY"
done

# ---------------------------------------------------------------------------
# 3. Build the markdown table and write to actions-versions.md
# ---------------------------------------------------------------------------
HEADER='| Action | Latest Major | Exact Tag | Last Checked |'
SEPARATOR='|--------|-------------|----------|-------------|'

TABLE_LINES=()
for action in "${ALL_ACTIONS[@]}"; do
  IFS='|' read -r tag major date <<< "${DATA[$action]}"
  [[ "$tag" == "N/A" || -z "$tag" ]] && continue
  printf -v row '| `%s` | %s | %s | %s |' "$action" "$major" "$tag" "$date"
  TABLE_LINES+=("$row")
done

NEW_CONTENT=$(cat <<EOF
<!-- actions-versions: auto-generated by update-actions-list.sh — DO NOT EDIT MANUALLY -->

${HEADER}
${SEPARATOR}
$(printf '%s\n' "${TABLE_LINES[@]}")
<!-- END -->
EOF
)

if [[ "$DRY_RUN" == true ]]; then
  echo ""
  echo "====== DRY RUN — would write to $VERSIONS_FILE ======"
  echo "$NEW_CONTENT"
  echo "====================================================="
  exit 0
fi

echo "$NEW_CONTENT" > "$VERSIONS_FILE"
echo ""
echo "✓ Updated $VERSIONS_FILE with ${#TABLE_LINES[@]} actions."
