#!/usr/bin/env bash
# ---------------------------------------------------------------------------
# update-actions-list.sh
#
# Uses `gh` CLI to discover all non-archived repos under github.com/actions/
# and fetch their latest release tags. Writes the result to:
#
#   <skill-dir>/actions-versions.md
#
# Prerequisites: `gh` authenticated (GH_TOKEN or gh auth login).
#
# Usage:
#   ./update-actions-list.sh [--dry-run] [--skill-dir <path>]
# ---------------------------------------------------------------------------
set -euo pipefail

DRY_RUN=false
SKILL_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"

while [[ $# -gt 0 ]]; do
  case "$1" in
    --dry-run)   DRY_RUN=true; shift ;;
    --skill-dir) SKILL_DIR="$2"; shift 2 ;;
    *) echo "Unknown arg: $1"; exit 1 ;;
  esac
done

VERSIONS_FILE="$SKILL_DIR/actions-versions.md"
TODAY=$(date +%Y-%m-%d)

# ---------------------------------------------------------------------------
# 1. Discover all non-archived repos from github.com/actions/
# ---------------------------------------------------------------------------
echo "==> Discovering repos from github.com/actions/ ..."

# gh api needs auth — show status for debugging
gh auth status 2>&1 || true

ALL_ACTIONS=()

# Write API output to a temp file first so errors are visible
TMP_JSON=$(mktemp)
trap 'rm -f "$TMP_JSON"' EXIT

if gh api --paginate "orgs/actions/repos?sort=stars&per_page=100" > "$TMP_JSON" 2>&1; then
  while IFS= read -r full_name; do
    [[ -z "$full_name" ]] && continue
    ALL_ACTIONS+=("$full_name")
  done < <(jq -r '.[] | select(.archived==false) | .full_name' "$TMP_JSON")
else
  echo "ERROR: gh api failed (see above). Trying fallback list..."
  # Fallback: hardcoded list of known actions/*
  ALL_ACTIONS=(
    actions/checkout
    actions/setup-go
    actions/setup-node
    actions/setup-python
    actions/setup-java
    actions/setup-dotnet
    actions/upload-artifact
    actions/download-artifact
    actions/cache
    actions/create-release
    actions/stale
    actions/labeler
    actions/first-interaction
    actions/github-script
    actions/setup-elixir
    actions/setup-haskell
    actions/setup-ruby
    actions/setup-php
    actions/delete-package-versions
    actions/runner-images
    actions/runner
    actions/toolkit
    actions/typescript-action
    actions/javascript-action
    actions/docker-action
    actions/hello-world-docker-action
    actions/hello-world-javascript-action
  )
fi

echo "==> Tracking ${#ALL_ACTIONS[@]} actions."

# ---------------------------------------------------------------------------
# 2. Fetch latest release tag for each action
# ---------------------------------------------------------------------------
declare -A DATA

echo "==> Fetching latest releases..."

for action in "${ALL_ACTIONS[@]}"; do
  printf '    %-45s ... ' "$action"

  tag=$(gh release view -R "$action" --json tagName -q '.tagName' 2>/dev/null || true)

  if [[ -z "$tag" ]]; then
    echo "no release"
    DATA["$action"]="N/A|N/A|$TODAY"
    continue
  fi

  major=$(echo "$tag" | sed -nE 's/^v?([0-9]+).*$/\1/p')
  [[ -z "$major" ]] && major="$tag"

  echo "$tag  (major: $major)"
  DATA["$action"]="$tag|$major|$TODAY"
done

# ---------------------------------------------------------------------------
# 3. Build the markdown table and write to actions-versions.md
# ---------------------------------------------------------------------------
HEADER='| Action | Latest Major | Exact Tag | Last Checked |'
SEPARATOR='|--------|-------------|----------|-------------|'

TABLE_LINES=()
for action in "${ALL_ACTIONS[@]}"; do
  IFS='|' read -r tag major date <<< "${DATA[$action]}"
  [[ "$tag" == "N/A" || -z "$tag" ]] && continue
  printf -v row '| `%s` | %s | %s | %s |' "$action" "$major" "$tag" "$date"
  TABLE_LINES+=("$row")
done

NEW_CONTENT=$(cat <<EOF
<!-- actions-versions: auto-generated by update-actions-list.sh — DO NOT EDIT MANUALLY -->

${HEADER}
${SEPARATOR}
$(printf '%s\n' "${TABLE_LINES[@]}")
<!-- END -->
EOF
)

if [[ "$DRY_RUN" == true ]]; then
  echo ""
  echo "====== DRY RUN — would write to $VERSIONS_FILE ======"
  echo "$NEW_CONTENT"
  echo "====================================================="
  exit 0
fi

echo "$NEW_CONTENT" > "$VERSIONS_FILE"
echo ""
echo "✓ Updated $VERSIONS_FILE with ${#TABLE_LINES[@]} actions."
